name: "Assemble"

on:
    pull_request:
        branches:
            - main
    push:

# Declare default permissions as read only.
permissions: read-all

jobs:
    flavor:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                flavor: [ Generic, Debug ]
        steps:
            -   uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
            -   name: set up JDK 18
                uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3
                with:
                    distribution: "temurin"
                    java-version: 18
            -   name: Build Project
                run: ./gradlew assemble

            -   name: Build ${{ matrix.flavor }}
                run: ./gradlew assemble${{ matrix.flavor }}
